import { Router } from "express";

import {
  getAudioUploads,
  getPublicAudioUploads,
  getPublicPlaylist,
  getPublicProfile,
  getRecommendedByProfile,
  getUserFollowers,
  getUserFollowersPublic,
  getUserFollowings,
  updateFollower,
} from "#/controllers/profile";
import { userIsAuth, userMustBeAuth } from "#/middlewares/auth";
import { getAutoGeneratedPlaylist } from "#/controllers/profile";

const router = Router();

router.post("/update-follower/:profileId", userMustBeAuth, updateFollower);
router.get("/audio-uploads", userMustBeAuth, getAudioUploads);
router.get("/audio-uploads/:profileId", getPublicAudioUploads);
router.get("/info/:profileId", getPublicProfile);
router.get("/playlist/:profileId", getPublicPlaylist);
router.get('/recommended', userIsAuth, getRecommendedByProfile);
router.get('/auto-generated-playlist', userMustBeAuth, getAutoGeneratedPlaylist);
router.get('/followers', userMustBeAuth, getUserFollowers);
router.get("/followers/:profileId", userMustBeAuth, getUserFollowersPublic);
router.get('/followings', userMustBeAuth, getUserFollowings);


export default router;
