import { RequestHandler } from "express";
import { isValidObjectId, ObjectId, PipelineStage, Types } from "mongoose";

import User from "#/models/user";
import { paginationQuery } from "#/types/miscellaneous";
import Audio, { AudioDocument } from "#/models/audio";
import Playlist from "#/models/playlist";
import History from "#/models/history";
import { getUserPrevHistory } from "#/utils/helper";
import AutoGeneratedPlaylist from "#/models/autoGeneratedPlaylist";

export const updateFollower: RequestHandler = async (req, res) => {
  const { profileId } = req.params;

  let status: "added" | "removed";

  if (!isValidObjectId(profileId)) {
    return res.status(422).json({ error: "Invalid Profile ID" });
  }

  const targetProfile = await User.findById(profileId);

  if (!targetProfile) {
    return res.status(404).json({ error: "Profile Not Found!" });
  }

  const alreadyAFollower = await User.findOne({
    _id: profileId,
    followers: req.user.id,
  });

  if (alreadyAFollower) {
    await User.updateOne(
      { _id: profileId },
      { $pull: { followers: req.user.id } }
    );

    status = "removed";
  } else {
    await User.updateOne(
      { _id: profileId },
      { $addToSet: { followers: req.user.id } }
    );

    status = "added";
  }

  if (status === "added") {
    await User.updateOne(
      { _id: req.user.id },
      { $addToSet: { followings: profileId } }
    );
  }

  if (status === "removed") {
    await User.updateOne(
      { _id: req.user.id },
      { $pull: { followings: profileId } }
    );
  }

  res.json({ status: status });
};

export const getAudioUploads: RequestHandler = async (req, res) => {
  const { pageNum = "0", limit = "10" } = req.query as paginationQuery;

  const targetAudios = await Audio.find({ owner: req.user.id })
    .skip(parseInt(limit) * parseInt(pageNum))
    .limit(parseInt(limit))
    .sort("-createdAt");

  const formattedAudios = targetAudios.map((audio) => {
    return {
      id: audio._id,
      title: audio.title,
      about: audio.about,
      file: audio.file.url,
      cateory: audio.category,
      poster: audio.poster?.url,
      date: audio.createdAt,
      owner: { name: req.user.name, id: req.user.id },
    };
  });

  res.json({ audios: formattedAudios });
};

export const getPublicAudioUploads: RequestHandler = async (req, res) => {
  const { pageNum = "0", limit = "10" } = req.query as paginationQuery;

  const { profileId } = req.params;

  if (!isValidObjectId(profileId)) {
    return res.status(422).json({ error: "Invalid Profile ID!" });
  }

  const targetAudios = await Audio.find({ owner: profileId })
    .skip(parseInt(limit) * parseInt(pageNum))
    .limit(parseInt(limit))
    .sort("-createdAt")
    .populate<AudioDocument<{ name: string; _id: ObjectId }>>("owner");

  const formattedAudios = targetAudios.map((audio) => {
    return {
      id: audio._id,
      title: audio.title,
      about: audio.about,
      file: audio.file.url,
      poster: audio.poster?.url,
      date: audio.createdAt,
      owner: { name: audio.owner.name, id: audio.owner._id },
    };
  });

  res.json({ audios: formattedAudios });
};

export const getPublicProfile: RequestHandler = async (req, res) => {
  const { profileId } = req.params;

  if (!isValidObjectId(profileId)) {
    return res.status(422).json({ error: "Invalid Profile ID!" });
  }

  const targetUser = await User.findById(profileId);

  if (!targetUser) {
    return res.status(422).json({ error: "User Not Found!" });
  }

  res.json({
    profile: {
      id: targetUser._id,
      name: targetUser.name,
      followers: targetUser.followers.length,
      avatar: targetUser.avatar?.url,
    },
  });
};

export const getPublicPlaylist: RequestHandler = async (req, res) => {
  const { profileId } = req.params;

  const { pageNum = "0", limit = "10" } = req.query as paginationQuery;

  if (!isValidObjectId(profileId)) {
    return res.status(422).json({ error: "Invalid Profile ID!" });
  }

  const targetPlaylist = await Playlist.find({
    owner: profileId,
    visibility: "public",
  })
    .skip(parseInt(limit) * parseInt(pageNum))
    .limit(parseInt(limit))
    .sort("-createdAt");

  if (!targetPlaylist) {
    return res.json({ playlist: [] });
  }

  const formattedPlaylist = targetPlaylist.map((p) => {
    return {
      id: p._id,
      title: p.title,
      songCount: p.items.length,
      visibility: p.visibility,
    };
  });

  res.json({ playlist: formattedPlaylist });
};

export const getRecommendedByProfile: RequestHandler = async (req, res) => {
  const user = req.user;

  let matchOptions: PipelineStage.Match = {
    $match: { _id: { $exists: true } },
  };

  if (user) {
    const category = await getUserPrevHistory(req);

    if (category.length) {
      matchOptions = { $match: { category: { $in: category } } };
    }
  }

  const audios = await Audio.aggregate([
    matchOptions,
    {
      $sort: {
        "likes.count": -1,
      },
    },
    {
      $limit: 10,
    },
    {
      $lookup: {
        from: "users",
        localField: "owner",
        foreignField: "_id",
        as: "owner",
      },
    },
    { $unwind: "$owner" },
    {
      $project: {
        _id: 0,
        id: "_id",
        title: "$title",
        about: "$about",
        category: "$category",
        file: "$file.url",
        poster: "$poster.url",
        owner: { name: "$owner.name", id: "$owner._id" },
      },
    },
  ]);

  res.json({ audios: audios });
};

export const getAutoGeneratedPlaylist: RequestHandler = async (req, res) => {
  //1 Mix 10

  const result = await History.aggregate([
    { $match: { owner: req.user.id } },
    { $unwind: "$all" },
    { $group: { _id: "$all.audio", items: { $addToSet: "$all.audio" } } },
    { $sample: { size: 10 } },
    { $group: { _id: null, items: { $push: "$_id" } } },
  ]);

  const title = "Mix 10";

  if (result) {
    await Playlist.updateOne(
      { owner: req.user.id, title: title },
      { $set: { title: title, items: result.items, visibility: "auto" } },
      { upsert: true }
    );
  }

  const category = await getUserPrevHistory(req);

  let matchOptions: PipelineStage.Match = {
    $match: { _id: { $exists: true } },
  };

  if (category.length) {
    matchOptions = { $match: { title: { $in: category } } };
  }

  const autoGenPlaylist = await AutoGeneratedPlaylist.aggregate([
    matchOptions,
    { $sample: { size: 4 } },
    {
      $project: {
        _id: 0,
        id: "$_id",
        title: "$title",
        itemCount: { $size: "$items" },
      },
    },
  ]);

  const playlist = await Playlist.findOne({ owner: req.user.id, title: title });

  const finalPlaylist = autoGenPlaylist.concat({
    id: playlist?._id,
    title: playlist?.title,
    itemsCount: playlist?.items.length,
  });

  res.json({ playlist: finalPlaylist });
};

export const getUserFollowers: RequestHandler = async (req, res) => {
  const { limit = "10", pageNum = "0" } = req.query as paginationQuery;

  const [result] = await User.aggregate([
    { $match: { _id: req.user.id } },
    {
      $project: {
        followers: {
          $slice: [
            "$followers",
            parseInt(pageNum) * parseInt(limit),
            parseInt(limit),
          ],
        },
      },
    },
    { $unwind: "$followers" },
    {
      $lookup: {
        from: "users",
        localField: "followers",
        foreignField: "_id",
        as: "userInfo",
      },
    },
    { $unwind: "$userInfo" },
    {
      $group: {
        _id: null,
        followers: {
          $push: {
            id: "$userInfo._id",
            name: "$userInfo.name",
            avatar: "$userInfo.avatar.url",
          },
        },
      },
    },
  ]);

  if (!result) {
    return res.json({ followers: [] });
  }

  res.json({ followers: result.followers });
};

export const getUserFollowings: RequestHandler = async (req, res) => {
  const { limit = "10", pageNum = "0" } = req.query as paginationQuery;

  const [result] = await User.aggregate([
    { $match: { _id: req.user.id } },
    {
      $project: {
        followings: {
          $slice: [
            "$followings",
            parseInt(pageNum) * parseInt(limit),
            parseInt(limit),
          ],
        },
      },
    },
    { $unwind: "$followings" },
    {
      $lookup: {
        from: "users",
        localField: "followings",
        foreignField: "_id",
        as: "userInfo",
      },
    },
    { $unwind: "$userInfo" },
    {
      $group: {
        _id: null,
        followings: {
          $push: {
            id: "$userInfo._id",
            name: "$userInfo.name",
            avatar: "$userInfo.avatar.url",
          },
        },
      },
    },
  ]);

  if (!result) {
    return res.json({ followings: [] });
  }

  res.json({ followings: result.followings });
};

export const getUserFollowersPublic: RequestHandler = async (req, res) => {
  const { limit = "10", pageNum = "0" } = req.query as paginationQuery;

  const { profileId } = req.params;

  if (!isValidObjectId(profileId)) {
    return res.status(422).json({ error: "Invalid Profile ID!" });
  }

  const [result] = await User.aggregate([
    { $match: { _id: new Types.ObjectId(profileId) } },
    {
      $project: {
        followers: {
          $slice: [
            "$followers",
            parseInt(pageNum) * parseInt(limit),
            parseInt(limit),
          ],
        },
      },
    },
    { $unwind: "$followers" },
    {
      $lookup: {
        from: "users",
        localField: "followers",
        foreignField: "_id",
        as: "userInfo",
      },
    },
    { $unwind: "$userInfo" },
    {
      $group: {
        _id: null,
        followers: {
          $push: {
            id: "$userInfo._id",
            name: "$userInfo.name",
            avatar: "$userInfo.avatar.url",
          },
        },
      },
    },
  ]);

  if (!result) {
    return res.json({ followers: [] });
  }

  res.json({ followers: result.followers });
};

export const getPlaylistAudios: RequestHandler = async (req, res) => {
  const { limit = "10", pageNum = "0" } = req.query as paginationQuery;

  const { playlistId } = req.params;

  if (!isValidObjectId(playlistId)) {
    return res.status(422).json({ error: "Invalid Playlist ID!" });
  }

  const aggregationLogic = [
    {
      $match: {
        _id: new Types.ObjectId(playlistId),
        visibility: { $ne: "private" },
      },
    },
    {
      $project: {
        items: {
          $slice: [
            "$items",
            parseInt(pageNum) * parseInt(limit),
            parseInt(limit),
          ],
        },
        title: "$title",
      },
    },
    {
      $unwind: "$items",
    },
    {
      $lookup: {
        from: "audios",
        localField: "items",
        foreignField: "_id",
        as: "audios",
      },
    },
    { $unwind: "$audios" },
    {
      $lookup: {
        from: "users",
        localField: "audios.owner",
        foreignField: "_id",
        as: "userInfo",
      },
    },
    { $unwind: "$userInfo" },
    {
      $group: {
        _id: {
          id: "$_id",
          title: "$title",
        },
        audios: {
          $push: {
            id: "$audios._id",
            title: "$audios.title",
            about: "$audios.about",
            category: "$audios.category",
            file: "$audios.file.url",
            poster: "$audios.poster.url",
            owner: { name: "$userInfo.name", id: "$userInfo._id" },
          },
        },
      },
    },
    {
      $project: {
        _id: 0,
        id: "$_id.id",
        title: "$_id.title",
        audios: "$$ROOT.audios",
      },
    },
  ];

  const [playlistResult] = await Playlist.aggregate(aggregationLogic);

  if (!playlistId) {
    const [autoPlaylistResult] = await AutoGeneratedPlaylist.aggregate(
      aggregationLogic
    );
    return res.json({ list: autoPlaylistResult });
  }

  res.json({ list: playlistResult });
};

export const getPrivatePlaylistAudios: RequestHandler = async (req, res) => {
  const { limit = "10", pageNum = "0" } = req.query as paginationQuery;

  const { playlistId } = req.params;

  if (!isValidObjectId(playlistId)) {
    return res.status(422).json({ error: "Invalid Playlist ID!" });
  }

  const aggregationLogic = [
    {
      $match: {
        _id: new Types.ObjectId(playlistId),
        owner: req.user.id,
      },
    },
    {
      $project: {
        items: {
          $slice: [
            "$items",
            parseInt(pageNum) * parseInt(limit),
            parseInt(limit),
          ],
        },
        title: "$title",
      },
    },
    {
      $unwind: "$items",
    },
    {
      $lookup: {
        from: "audios",
        localField: "items",
        foreignField: "_id",
        as: "audios",
      },
    },
    { $unwind: "$audios" },
    {
      $lookup: {
        from: "users",
        localField: "audios.owner",
        foreignField: "_id",
        as: "userInfo",
      },
    },
    { $unwind: "$userInfo" },
    {
      $group: {
        _id: {
          id: "$_id",
          title: "$title",
        },
        audios: {
          $push: {
            id: "$audios._id",
            title: "$audios.title",
            about: "$audios.about",
            category: "$audios.category",
            file: "$audios.file.url",
            poster: "$audios.poster.url",
            owner: { name: "$userInfo.name", id: "$userInfo._id" },
          },
        },
      },
    },
    {
      $project: {
        _id: 0,
        id: "$_id.id",
        title: "$_id.title",
        audios: "$$ROOT.audios",
      },
    },
  ];

  const [playlistResult] = await Playlist.aggregate(aggregationLogic);

  if (!playlistId) {
    const [autoPlaylistResult] = await AutoGeneratedPlaylist.aggregate(
      aggregationLogic
    );
    return res.json({ list: autoPlaylistResult });
  }

  res.json({ list: playlistResult });
};

export const getIsFollowing: RequestHandler = async (req, res) => {
  const { profileId } = req.params;

  if (!isValidObjectId(profileId)) {
    return res.status(422).json({ error: "Invalid Profile ID!" });
  }

  const user = await User.findOne({ _id: profileId, followers: req.user.id });

  res.json({ status: user ? true : false });
};
